01-django-locallibrary/app/catalog/urls.py
from django.urls import path

from . import views


urlpatterns = [
    path("", views.index, name="index"),
    path("books/", views.BookListView.as_view(), name="books"),
    path("book/<int:pk>", views.BookDetailView.as_view(), name="book-detail"),
    path("authors/", views.AuthorListView.as_view(), name="authors"),
    path("author/<int:pk>", views.AuthorDetailView.as_view(), name="author-detail"),
]


urlpatterns += [
    path("mybooks/", views.LoanedBooksByUserListView.as_view(), name="my-borrowed"),
    path(
        r"borrowed/", views.LoanedBooksAllListView.as_view(), name="all-borrowed"
    ),  # Added for challenge
]


# Add URLConf for librarian to renew a book.
urlpatterns += [
    path(
        "book/<uuid:pk>/renew/", views.renew_book_librarian, name="renew-book-librarian"
    ),
]


# Add URLConf to create, update, and delete authors
urlpatterns += [
    path("author/create/", views.AuthorCreate.as_view(), name="author-create"),
    path("author/<int:pk>/update/", views.AuthorUpdate.as_view(), name="author-update"),
    path("author/<int:pk>/delete/", views.AuthorDelete.as_view(), name="author-delete"),
]

# Add URLConf to create, update, and delete books
urlpatterns += [
    path("book/create/", views.BookCreate.as_view(), name="book-create"),
    path("book/<int:pk>/update/", views.BookUpdate.as_view(), name="book-update"),
    path("book/<int:pk>/delete/", views.BookDelete.as_view(), name="book-delete"),
]


# Add URLConf to list, view, create, update, and delete genre
urlpatterns += [
    path("genres/", views.GenreListView.as_view(), name="genres"),
    path("genre/<int:pk>", views.GenreDetailView.as_view(), name="genre-detail"),
    path("genre/create/", views.GenreCreate.as_view(), name="genre-create"),
    path("genre/<int:pk>/update/", views.GenreUpdate.as_view(), name="genre-update"),
    path("genre/<int:pk>/delete/", views.GenreDelete.as_view(), name="genre-delete"),
]

# Add URLConf to list, view, create, update, and delete languages
urlpatterns += [
    path("languages/", views.LanguageListView.as_view(), name="languages"),
    path(
        "language/<int:pk>", views.LanguageDetailView.as_view(), name="language-detail"
    ),
    path("language/create/", views.LanguageCreate.as_view(), name="language-create"),
    path(
        "language/<int:pk>/update/",
        views.LanguageUpdate.as_view(),
        name="language-update",
    ),
    path(
        "language/<int:pk>/delete/",
        views.LanguageDelete.as_view(),
        name="language-delete",
    ),
]

# Add URLConf to list, view, create, update, and delete bookinstances
urlpatterns += [
    path("bookinstances/", views.BookInstanceListView.as_view(), name="bookinstances"),
    path(
        "bookinstance/<uuid:pk>",
        views.BookInstanceDetailView.as_view(),
        name="bookinstance-detail",
    ),
    path(
        "bookinstance/create/",
        views.BookInstanceCreate.as_view(),
        name="bookinstance-create",
    ),
    path(
        "bookinstance/<uuid:pk>/update/",
        views.BookInstanceUpdate.as_view(),
        name="bookinstance-update",
    ),
    path(
        "bookinstance/<uuid:pk>/delete/",
        views.BookInstanceDelete.as_view(),
        name="bookinstance-delete",
    ),
]

01-django-locallibrary/app/catalog/models.py
from django.db import models

# Create your models here.

from django.urls import reverse  # To generate URLS by reversing URL patterns


class Genre(models.Model):
    """Model representing a book genre (e.g. Science Fiction, Non Fiction)."""

    name = models.CharField(
        max_length=200,
        unique=True,
        help_text="Enter a book genre (e.g. Science Fiction, French Poetry etc.)",
    )

    def get_absolute_url(self):
        """Returns the url to access a particular genre instance."""
        return reverse("genre-detail", args=[str(self.id)])

    def __str__(self):
        """String for representing the Model object (in Admin site etc.)"""
        return self.name


class Language(models.Model):
    """Model representing a Language (e.g. English, French, Japanese, etc.)"""

    name = models.CharField(
        max_length=200,
        unique=True,
        help_text="Enter the book's natural language (e.g. English, French, Japanese etc.)",
    )

    def get_absolute_url(self):
        """Returns the url to access a particular language instance."""
        return reverse("language-detail", args=[str(self.id)])

    def __str__(self):
        """String for representing the Model object (in Admin site etc.)"""
        return self.name


class Book(models.Model):
    """Model representing a book (but not a specific copy of a book)."""

    title = models.CharField(max_length=200)
    author = models.ForeignKey("Author", on_delete=models.RESTRICT, null=True)
    # Foreign Key used because book can only have one author, but authors can have multiple books.
    # Author as a string rather than object because it hasn't been declared yet in file.
    summary = models.TextField(
        max_length=1000, help_text="Enter a brief description of the book"
    )
    isbn = models.CharField(
        "ISBN",
        max_length=13,
        unique=True,
        help_text='13 Character <a href="https://www.isbn-international.org/content/what-isbn'
        '">ISBN number</a>',
    )
    genre = models.ManyToManyField(Genre, help_text="Select a genre for this book")
    # ManyToManyField used because a genre can contain many books and a Book can cover many genres.
    # Genre class has already been defined so we can specify the object above.
    language = models.ForeignKey("Language", on_delete=models.SET_NULL, null=True)

    class Meta:
        ordering = ["title", "author"]

    def display_genre(self):
        """Creates a string for the Genre. This is required to display genre in Admin."""
        return ", ".join([genre.name for genre in self.genre.all()[:3]])

    display_genre.short_description = "Genre"

    def get_absolute_url(self):
        """Returns the url to access a particular book record."""
        return reverse("book-detail", args=[str(self.id)])

    def __str__(self):
        """String for representing the Model object."""
        return self.title


import uuid  # Required for unique book instances
from datetime import date

from django.conf import settings  # Required to assign User as a borrower


class BookInstance(models.Model):
    """Model representing a specific copy of a book (i.e. that can be borrowed from the library)."""

    id = models.UUIDField(
        primary_key=True,
        default=uuid.uuid4,
        help_text="Unique ID for this particular book across whole library",
    )
    book = models.ForeignKey("Book", on_delete=models.RESTRICT, null=True)
    imprint = models.CharField(max_length=200)
    due_back = models.DateField(null=True, blank=True)
    borrower = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, null=True, blank=True
    )

    @property
    def is_overdue(self):
        """Determines if the book is overdue based on due date and current date."""
        return bool(self.due_back and date.today() > self.due_back)

    LOAN_STATUS = (
        ("d", "Maintenance"),
        ("o", "On loan"),
        ("a", "Available"),
        ("r", "Reserved"),
    )

    status = models.CharField(
        max_length=1,
        choices=LOAN_STATUS,
        blank=True,
        default="d",
        help_text="Book availability",
    )

    class Meta:
        ordering = ["due_back"]
        permissions = (("can_mark_returned", "Set book as returned"),)

    def get_absolute_url(self):
        """Returns the url to access a particular book instance."""
        return reverse("bookinstance-detail", args=[str(self.id)])

    def __str__(self):
        """String for representing the Model object."""
        return f"{self.id} ({self.book.title})"


class Author(models.Model):
    """Model representing an author."""

    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    date_of_birth = models.DateField(null=True, blank=True)
    date_of_death = models.DateField("died", null=True, blank=True)

    class Meta:
        ordering = ["last_name", "first_name"]

    def get_absolute_url(self):
        """Returns the url to access a particular author instance."""
        return reverse("author-detail", args=[str(self.id)])

    def __str__(self):
        """String for representing the Model object."""
        return f"{self.last_name}, {self.first_name}"

01-django-locallibrary/app/catalog/templates/base_generic.html
<!DOCTYPE html>
<html lang="en">
<head>

  {% block title %}<title>Local Library</title>{% endblock %}
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">

  <!-- Add additional CSS in static file -->
  {% load static %}
  <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>
<body>

<div class="container-fluid">

<div class="row">
  <div class="col-sm-2">
  {% block sidebar %}
  <ul class="sidebar-nav">
    <li><a href="{% url 'index' %}">Home</a></li>
    <li><a href="{% url 'bookinstances' %}">All book copies</a></li>
    <li><a href="{% url 'books' %}">All books</a></li>
    <li><a href="{% url 'authors' %}">All authors</a></li>
    <li><a href="{% url 'genres' %}">All genres</a></li>
    <li><a href="{% url 'languages' %}">All languages</a></li>
  </ul>

  <ul class="sidebar-nav">
   {% if user.is_authenticated %}
     <li>User: {{ user.get_username }}</li>
     <li><a href="{% url 'my-borrowed' %}">My borrowed</a></li>
     <li><a href="{% url 'logout'%}?next={{request.path}}">Logout</a></li>
   {% else %}
     <li><a href="{% url 'login'%}?next={{request.path}}">Login</a></li>
   {% endif %}
  </ul>

   {% if user.is_staff %}
   <hr>
   <ul class="sidebar-nav">
   <li>Staff</li>
   <li><a href="{% url 'all-borrowed' %}">All borrowed</a></li>
   {% if perms.catalog.add_genre %}
     <li><a href="{% url 'genre-create' %}">Create genre</a></li>
   {% endif %}
   {% if perms.catalog.add_genre %}
     <li><a href="{% url 'language-create' %}">Create language</a></li>
   {% endif %}
   {% if perms.catalog.add_author %}
     <li><a href="{% url 'author-create' %}">Create author</a></li>
   {% endif %}
   {% if perms.catalog.add_book %}
     <li><a href="{% url 'book-create' %}">Create book</a></li>
   {% endif %}
   {% if perms.catalog.add_bookinstance %}
     <li><a href="{% url 'bookinstance-create' %}">create BookInstance</a></li>
   {% endif %}
   </ul>
   {% endif %}

{% endblock %}
  </div>
  <div class="col-sm-10 ">
  {% block content %}{% endblock %}

  {% block pagination %}
    {% if is_paginated %}
        <div class="pagination">
            <span class="page-links">
                {% if page_obj.has_previous %}
                    <a href="{{ request.path }}?page={{ page_obj.previous_page_number }}">previous</a>
                {% endif %}
                <span class="page-current">
                    Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                </span>
                {% if page_obj.has_next %}
                    <a href="{{ request.path }}?page={{ page_obj.next_page_number }}">next</a>
                {% endif %}
            </span>
        </div>
    {% endif %}
  {% endblock %}
  </div>
</div>

</div>
</body>
</html>

01-django-locallibrary/app/catalog/templates/index.html
{% extends "base_generic.html" %}

{% block content %}
<h1>Local Library Home</h1>

<h2>UML Models</h2>
<p>An UML diagram of the site's Django model structure is shown below. </p>

<div>
{% load static %}
<img src="{% static 'images/local_library_model_uml.png' %}" alt="My image" width="600px">
</div>


<h2>Dynamic content</h2>

<p>The library has the following record counts:</p>
<ul>
<li><strong>Books:</strong> {{ num_books }}</li>
<li><strong>Copies:</strong> {{ num_instances }}</li>
<li><strong>Copies available:</strong> {{ num_instances_available }}</li>
<li><strong>Authors:</strong> {{ num_authors }}</li>
</ul>


<p>You have visited this page {{ num_visits }} time{{ num_visits|pluralize }}.</p>

{% endblock %}